version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo $CIRCLE_BRANCH
            echo $CIRCLE_TAG
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              echo "I would push this as $BRANCH_OR_TAG"
            else
              echo "I am not a tag"
            fi

workflows:
  version: 2
  build_test:
    jobs:
      - build
