# 1. Set your default branch to develop
# 2. In circleci project settings->advanced set:
#    - GitHub Status Updates (this should be on already)
#    - Only build pull requests
#    - Auto-cancel redundant builds
#    - Free and Open Source (this should be on already)

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo $CIRCLE_BRANCH
            echo $CIRCLE_TAG
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              echo "I would push this as $BRANCH_OR_TAG"
            else
              echo "I am not a tag"
            fi

workflows:
  version: 2.1
  build_test:
    jobs:
      - build:
        filters:
          tags:
            only: /.+/
